all: 
	g++ -o imageRestoration imageRestoration.cpp -lglut -lGLU -lGL -lm

run:
	./imageRestoration ./entradas/cidade.bmp
	./imageRestoration ./entradas/porta.bmp
	./imageRestoration ./entradas/impressao_digital.bmp
	./imageRestoration ./entradas/picture_1_entrada.bmp
	./imageRestoration ./entradas/picture_2_entrada.bmp
	./imageRestoration ./entradas/picture_3_entrada.bmp
	./imageRestoration ./entradas/picture_4_entrada.bmp
	./imageRestoration ./entradas/picture_5_entrada.bmp

